language: ruby

sudo: false
language: ruby
cache: bundler
script: "TESTOPTS=-v bundle exec rake test"

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.1.2
  - 2.2
  - jruby-19mode
  - jruby-head
  - rbx-2
  - rbx-1

matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: rbx-1
    - rvm: 1.8.7

script: "rake test"


